node { 
    def app
    stage('Checkout code') {
        checkout scm
    }
//            export IMAGE="${env.BUILD_NUMBER}"
    withEnv(['HOST=eu.gcr.io/crafty-clover-301509/unoterr1/blog_comp:']){
        stage('Build and Push') {
            sh "#!/bin/zsh \n" +
            """
            export HOST="${env.HOST}"
            export IMAGE="latest"
            cd blog && envsubst < docker-tmp.yml > docker-compose.yml 
            docker-compose build blog
            docker-compose push blog
            """.stripIndent()
        }
    }
    stage('Create cluster') {
        sh """
        cd terraform/cluster
        terraform init
        terraform apply
        """
    }
    stage('Deploy') {
        sh """
        cd terraform/k8s
        terraform init
        terraform apply
        """
    }
/*
    withCredentials([string(credentialsId: 'HOST', variable: 'HOST'),
        string(credentialsId: 'USER', variable: 'USER'),
        string(credentialsId: 'PASS', variable: 'PASS'),
        string(credentialsId: 'NAME', variable: 'NAME')]) {
            stage('Deploy App') {


            sh """
            export IMAGE="${env.BUILD_NUMBER}"
            cd blog && envsubst < blog.yaml > blog_tmp.yaml
            kubectl apply -f blog_tmp.yaml
            """.stripIndent()

        }
    }
*/
}
